=== rohilnain/Pluggin-Adobe/Acrobat_DC_SDK_Windows_2021_v2/Adobe/Acrobat DC SDK/Version 1/OtherSupport/SaveAsXML/Advanced/MappingTable.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- This is the DTD for SaveAsXML, last modified 28-February-2003 -->
<!--
	ADOBE SYSTEMS INCORPORATED
	Copyright 2003 Adobe Systems Incorporated
	All Rights Reserved
	
	NOTICE:  This Notice only applies to this file or any portion thereof.
	Adobe permits you to use, modify, and distribute this file in accordance
	with the terms and conditions of the Adobe license agreement accompanying
	it ("Agreement").  Additionally, Adobe grants you a nonexclusive,
	nontransferable, royalty-free license to use, modify and distribute
	all or any portion of this file.  Where the terms of this Notice
	and the terms of the Agreement differ, the terms of this Notice
	shall control.  All other terms and conditions of the Agreement
	remain unchanged and have full force and effect.  If you have received
	this file from a source other than Adobe, then your use, modification,
	or distribution of it requires the prior written permission of Adobe.
-->
<!ELEMENT Root ((Comment | Emit-string | Define-event-list | Define-proc-list | Walk-doc-metadata | Emit-doc-metadata | Walk-cached-property-sets | Walk-structure | Walk-bookmarks | Set-encoding | Emit-encoding | Begin-encoding)+)>
<!ATTLIST Root
	File-format CDATA #REQUIRED
	Menu-name CDATA #REQUIRED
	Mac-creator CDATA #REQUIRED
	Mac-type CDATA #REQUIRED
	Win-suffix CDATA #REQUIRED
	Encode-out (Ucs-2-out | Ucs-4-out | Utf-8-out | Utf-16-out | Iso-latin-1-out | Html-ascii-out | Host-code-out) #REQUIRED
>
<!ELEMENT Walk-doc-metadata (Void?)>
<!ATTLIST Walk-doc-metadata
	Use-proc-list CDATA #REQUIRED
>
<!ELEMENT Emit-doc-metadata (Void?)>
<!ATTLIST Emit-doc-metadata
	SP-Before (Yes | No) #IMPLIED
	SP-After (Yes | No) #IMPLIED
	NL-Before (Yes | No) #IMPLIED
	NL-After (Yes | No) #IMPLIED
>
<!ELEMENT Emit-metadata (Void?)>
<!ATTLIST Emit-metadata
	SP-Before (Yes | No) #IMPLIED
	SP-After (Yes | No) #IMPLIED
	NL-Before (Yes | No) #IMPLIED
	NL-After (Yes | No) #IMPLIED
>
<!ELEMENT Walk-structure (Void?)>
<!ATTLIST Walk-structure
	Use-event-list CDATA #REQUIRED
>
<!ELEMENT Walk-cached-property-sets (Void?)>
<!ATTLIST Walk-cached-property-sets
	Use-event-list CDATA #REQUIRED
>
<!ELEMENT Walk-children (Void?)>
<!ATTLIST Walk-children
	Use-event-list CDATA #REQUIRED
>
<!ELEMENT Walk-bookmarks (Void?)>
<!ATTLIST Walk-bookmarks
	Use-event-list CDATA #REQUIRED
>
<!ELEMENT Define-event-list ((Comment | Event | Call-event-list)+)>
<!ATTLIST Define-event-list
	Name CDATA #REQUIRED
>
<!ELEMENT Call-event-list (Void?)>
<!ATTLIST Call-event-list
	Name CDATA #REQUIRED
>
<!ELEMENT Event ((Comment | Emit-string | Conditional-prefix | Conditional-delimeter | Element-name | Evaluate-var | Proc-var | Walk-proplist | Call-proc-list | Conditional-suffix | Proc-graphic-content | Proc-image-content | Proc-doc-text | Walk-children | Emit-metadata)+)>
<!ATTLIST Event
	Inf-type (Root | Struct-elem | Pds-mc | Obj-ref | Bookmark) #REQUIRED
	Name-type (Any | Structure-role | Structure-user-label) #REQUIRED
	Node-name CDATA "-none-"
	Alternate-name CDATA "-none-"
	Node-content (Empty | Has-text-only | Has-kids | Graphic | Image | Bookmark | Other) #REQUIRED
	Event-class (Enter | Enter-from-parent | Enter-from-peer | Exit | Exit-to-parent | Exit-to-peer | Begin-children | End-children) #REQUIRED
>
<!ELEMENT Define-proc-list ((Comment | Evaluate-var | Proc-var | Walk-proplist | Call-proc-list | Conditional-prefix | Conditional-suffix | Proc-property)+)>
<!ATTLIST Define-proc-list
	Name CDATA #REQUIRED
>
<!ELEMENT Call-proc-list (Void?)>
<!ATTLIST Call-proc-list
	Name CDATA #REQUIRED
>
<!ELEMENT Proc-var ((Comment | Emit-string | Conditional-prefix | Conditional-delimeter | Element-name | Proc-string | Proc-integer | Proc-hex | Proc-fixed | Proc-length | Proc-pixels | Proc-color | Proc-enum | Evaluate-var | Proc-var | Walk-proplist | Call-proc-list | Proc-graphic-content | Proc-image-content | Proc-bookmark-target | Proc-doc-text | Walk-children | Walk-cached-property-sets | Walk-structure | Conditional-suffix | Walk-doc-metadata)+)>
<!ATTLIST Proc-var
	Pdf-var CDATA #REQUIRED
	Owner (Metadata | Structelem | Layout | Link | List | Table | AutoTextStyle | Inline-markup) #REQUIRED
	Type (Fixed | Int32 | Atom | String | Color) #REQUIRED
	Has-enum (Enum | No-enum) #IMPLIED
	Inherit (Inheritable | Not-inherited) #REQUIRED
	Default CDATA #IMPLIED
	Condition (Always | Has-value | No-value | Diff-from-default-for-event | Diff-from-default-or-parent | Diff-from-parent | Diff-from-predecessor | Diff-from-value | Matches-value | Less-than-value | More-than-value | Less-equal-value | More-equal-value | Is-bookmark-target) #REQUIRED
	Compare CDATA "-none-"
>
<!ELEMENT Evaluate-var ((Comment | Emit-string | Conditional-prefix | Conditional-delimeter | Element-name | Proc-string | Proc-integer | Proc-hex | Proc-fixed | Proc-length | Proc-pixels | Proc-color | Proc-enum | Evaluate-var | Proc-var | Walk-proplist | Call-proc-list | Proc-graphic-content | Proc-image-content | Proc-bookmark-target | Proc-doc-text | Walk-children | Walk-cached-property-sets | Walk-structure | Conditional-suffix | Walk-doc-metadata)+)>
<!ATTLIST Evaluate-var
	Pdf-var CDATA #REQUIRED
	Owner (Metadata | Structelem | Layout | Link | List | Table | AutoTextStyle | Inline-markup | Style-cache) #REQUIRED
	Type (Fixed | Int32 | Atom | String | Color | Constant) #REQUIRED
	Has-enum (Enum | No-enum) #IMPLIED
	Inherit (Inheritable | Not-inherited) #REQUIRED
	Default CDATA #IMPLIED
	Condition (Always | Has-value | No-value | Diff-from-default-for-event | Diff-from-default-or-parent | Diff-from-parent | Diff-from-predecessor | Diff-from-value | Matches-value | Less-than-value | More-than-value | Less-equal-value | More-equal-value | Is-bookmark-target) #REQUIRED
	Compare CDATA "-none-"
>
<!ELEMENT Walk-proplist (Void?)>
<!ATTLIST Walk-proplist
	Owner (XML-1.00 | HTML-3.20 | HTML-4.01 | OEB-1.00 | RTF-1.05 | CSS-1.00 | CSS-2.00 | XHTML-1.00) #REQUIRED
	Use-proclist CDATA #REQUIRED
>
<!ELEMENT Proc-property ((Comment | Conditional-delimeter | Emit-string | Property-name | Property-type)+)>
<!ELEMENT Property-type ((Comment | Conditional-delimeter | Emit-string | Proc-string | Proc-integer | Proc-hex | Proc-fixed | Proc-length | Proc-pixels | Proc-enum | Proc-doc-text | Proc-graphic-content | Proc-image-content)+)>
<!ATTLIST Property-type
	Type (Fixed | Int32 | Atom | String) #REQUIRED
>
<!ELEMENT Property-name (Void?)>
<!ELEMENT Element-name (Void?)>
<!ATTLIST Element-name
	Name-type (Any | Structure-role | Structure-user-label) #REQUIRED
>
<!ELEMENT Conditional-delimeter (#PCDATA)>
<!ATTLIST Conditional-delimeter
	SP-Before (Yes | No) #IMPLIED
	SP-After (Yes | No) #IMPLIED
	NL-Before (Yes | No) #IMPLIED
	NL-After (Yes | No) #IMPLIED
>
<!ELEMENT Conditional-prefix (#PCDATA)>
<!ATTLIST Conditional-prefix
	SP-Before (Yes | No) #IMPLIED
	SP-After (Yes | No) #IMPLIED
	NL-Before (Yes | No) #IMPLIED
	NL-After (Yes | No) #IMPLIED
>
<!ELEMENT Conditional-suffix (#PCDATA)>
<!ATTLIST Conditional-suffix
	SP-Before (Yes | No) #IMPLIED
	SP-After (Yes | No) #IMPLIED
	NL-Before (Yes | No) #IMPLIED
	NL-After (Yes | No) #IMPLIED
>
<!ELEMENT Comment (#PCDATA)>
<!ELEMENT Emit-string (#PCDATA)>
<!ATTLIST Emit-string
	SP-Before (Yes | No) #IMPLIED
	SP-After (Yes | No) #IMPLIED
	NL-Before (Yes | No) #IMPLIED
	NL-After (Yes | No) #IMPLIED
	Expand-entities (Expand-entities | No-entities) "No-entities"
>
<!ELEMENT Proc-doc-text (Void?)>
<!ATTLIST Proc-doc-text
	do-br-substitution (do-br-substitution | do-xml-br-substitution | no-substitution) #REQUIRED
	Expand-entities (Expand-entities | No-entities) "No-entities"
	ToEscape CDATA #IMPLIED
	EscapeWith CDATA #IMPLIED
>
<!ELEMENT Proc-string (Void?)>
<!ATTLIST Proc-string
	Expand-entities (Expand-entities | No-entities) "No-entities"
>
<!ELEMENT Proc-integer (Void?)>
<!ATTLIST Proc-integer
	Mul CDATA "1"
	Add CDATA "0"
	Div CDATA "1"
>
<!ELEMENT Proc-hex (Void?)>
<!ATTLIST Proc-hex
	Mul CDATA "1"
	Add CDATA "0"
	Div CDATA "1"
	Num-digits CDATA "1"
>
<!ELEMENT Proc-fixed (Void?)>
<!ATTLIST Proc-fixed
	Mul CDATA "1"
	Add CDATA "0"
	Div CDATA "1"
	Frac-len CDATA "2"
	Frac-dlm CDATA "."
>
<!ELEMENT Proc-length (Void?)>
<!ATTLIST Proc-length
	Mul CDATA "72"
	Add CDATA "0"
	Div CDATA "72"
	Frac-len CDATA "2"
	Frac-dlm CDATA "."
>
<!ELEMENT Proc-pixels (Void?)>
<!ATTLIST Proc-pixels
	Mul CDATA "96"
	Add CDATA "36"
	Div CDATA "72"
	Frac-len CDATA "0"
	Frac-dlm CDATA "."
>
<!ELEMENT Proc-color (Void?)>
<!ATTLIST Proc-color
	OutputHex (Yes | No) #REQUIRED
	Uppercase (Yes | No) #IMPLIED
>
<!ELEMENT Proc-enum (Proc-enum-choice+)>
<!ELEMENT Proc-enum-choice (Void?)>
<!ATTLIST Proc-enum-choice
	Value-in CDATA #REQUIRED
	Value-out CDATA #REQUIRED
>
<!ELEMENT Proc-graphic-content (Void?)>
<!ELEMENT Proc-image-content (Void?)>
<!ELEMENT Proc-bookmark-target (Void?)>
<!ELEMENT Set-encoding (Enum-encoding+)>
<!ELEMENT Enum-encoding (Void?)>
<!ATTLIST Enum-encoding
	Type CDATA #REQUIRED
	Suppress (Yes | No) #IMPLIED
	Emit-BOM (Yes | No) #IMPLIED
>
<!ELEMENT Emit-encoding (Proc-enum?)>
<!ELEMENT Begin-encoding (Void?)>
<!--Void: The "Void" node is used to avoid the <empty/> syntax.-->
<!ELEMENT Void EMPTY>

=== rohilnain/Pluggin-Adobe/Acrobat_DC_SDK_Windows_2021_v2/Adobe/Acrobat DC SDK/Version 1/OtherSupport/SaveAsXML/SDKImageExtraction.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Root SYSTEM "MappingTable.dtd"><Root File-format="MDF" Menu-name="SDK Image Extraction" Mac-creator="" Mac-type="TEXT" Win-suffix="xxx.txt" Encode-out="Utf-8-out">	<!--	ADOBE SYSTEMS INCORPORATED	Copyright 2003 Adobe Systems Incorporated	All Rights Reserved		NOTICE:  This Notice only applies to this file or any portion thereof.	Adobe permits you to use, modify, and distribute this file in accordance	with the terms and conditions of the Adobe license agreement accompanying	it ("Agreement").  Additionally, Adobe grants you a nonexclusive,	nontransferable, royalty-free license to use, modify and distribute	all or any portion of this file.  Where the terms of this Notice	and the terms of the Agreement differ, the terms of this Notice	shall control.  All other terms and conditions of the Agreement	remain unchanged and have full force and effect.  If you have received	this file from a source other than Adobe, then your use, modification,	or distribution of it requires the prior written permission of Adobe.-->	<!-- This example will extract images into a sub-folder and create a plain text file of the images extracted, along with their width and height. -->	<Define-proc-list Name="Figure-attributes">		<!-- We get the height and the width from either the layout or the document structure -->		<Proc-var Pdf-var="Width" Owner="Layout" Type="Fixed" Inherit="Not-inherited" Condition="Has-value">			<Emit-string SP-Before="Yes">width=&quot;</Emit-string>			<Proc-pixels/>			<Emit-string>&quot;</Emit-string>		</Proc-var>		<Proc-var Pdf-var="Width" Owner="Layout" Type="Fixed" Inherit="Not-inherited" Condition="No-value">			<Proc-var Pdf-var="Width" Owner="Structelem" Type="Fixed" Inherit="Not-inherited" Condition="Has-value">				<Emit-string SP-Before="Yes">Width=&quot;</Emit-string>				<Proc-pixels/>				<Emit-string>&quot;</Emit-string>			</Proc-var>		</Proc-var>		<Proc-var Pdf-var="Height" Owner="Layout" Type="Fixed" Inherit="Not-inherited" Condition="Has-value">			<Emit-string SP-Before="Yes">height=&quot;</Emit-string>			<Proc-pixels/>			<Emit-string>&quot;</Emit-string>		</Proc-var>		<Proc-var Pdf-var="Height" Owner="Layout" Type="Fixed" Inherit="Not-inherited" Condition="No-value">			<Proc-var Pdf-var="Height" Owner="Structelem" Type="Fixed" Inherit="Not-inherited" Condition="Has-value">				<Emit-string SP-Before="Yes">height=&quot;</Emit-string>				<Proc-pixels/>				<Emit-string>&quot;</Emit-string>			</Proc-var>		</Proc-var>	</Define-proc-list>		<Define-event-list Name="content-elements">		<!-- For images, we dump their attributes. -->		<Event Inf-type="Struct-elem" Name-type="Structure-role" Node-name="Figure" Alternate-name="Img" Node-content="Has-kids" Event-class="Enter">			<Emit-string SP-After="Yes">Extracted image:</Emit-string>			<Call-proc-list Name="Figure-attributes"/>			<Emit-string SP-Before="Yes">file=&quot;</Emit-string>			<Proc-image-content/>			<Emit-string NL-After="Yes">&quot;</Emit-string>		</Event>		<!-- walk the structure... -->		<Event Inf-type="Struct-elem" Name-type="Any" Node-content="Has-kids" Event-class="Enter">			<Walk-children Use-event-list="content-elements"/>		</Event>	</Define-event-list>	<!-- Walk the structure tree -->	<Walk-structure Use-event-list="content-elements"/></Root>

=== rohilnain/Pluggin-Adobe/Acrobat_DC_SDK_Windows_2021_v2/Adobe/Acrobat DC SDK/Version 1/OtherSupport/SaveAsXML/SDKTextExtraction.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Root SYSTEM "MappingTable.dtd"><Root File-format="MDF" Menu-name="SDK Text Extraction" Mac-creator="" Mac-type="TEXT" Win-suffix="xxx.txt" Encode-out="Utf-8-out">	<!--	ADOBE SYSTEMS INCORPORATED	Copyright 2003 Adobe Systems Incorporated	All Rights Reserved		NOTICE:  This Notice only applies to this file or any portion thereof.	Adobe permits you to use, modify, and distribute this file in accordance	with the terms and conditions of the Adobe license agreement accompanying	it ("Agreement").  Additionally, Adobe grants you a nonexclusive,	nontransferable, royalty-free license to use, modify and distribute	all or any portion of this file.  Where the terms of this Notice	and the terms of the Agreement differ, the terms of this Notice	shall control.  All other terms and conditions of the Agreement	remain unchanged and have full force and effect.  If you have received	this file from a source other than Adobe, then your use, modification,	or distribution of it requires the prior written permission of Adobe.-->	<!-- 	This is the about the simplest mapping table that actually does something. It extracts the text from the document 	and saves it to a file with the suffix ".xxx.txt". The order text is output in is the order it appears in the stream. 	Place this file in the "MappingTables" folder found alongside the SaveAsXML plug-in (API) file. -->	<!-- The event list deals with just two events. Entering a structure element that has kids, and text nodes. 	 -->	<Define-event-list Name="content-elements">		<!-- Deal with the structure nodes -->		<Event Inf-type="Struct-elem" Name-type="Any" Node-content="Has-kids" Event-class="Enter">			<!-- For each structure with children, recurse, walking the child nodes -->			<Walk-children Use-event-list="content-elements"/>		</Event>		<!-- Deal with the text-only nodes. -->		<Event Inf-type="Pds-mc" Name-type="Any" Node-content="Has-text-only" Event-class="Enter">			<!-- Output text -->			<Proc-doc-text do-br-substitution="no-substitution"/>			<!-- Followed by a newline. -->			<Emit-string NL-After="Yes"/>		</Event>	</Define-event-list>	<!-- Walk the strructure tree -->	<Walk-structure Use-event-list="content-elements"/></Root>

=== rohilnain/Pluggin-Adobe/Acrobat_DC_SDK_Windows_2021_v2/Adobe/Acrobat DC SDK/Version 1/OtherSupport/SaveAsXML/SDKDocInfoExtraction.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Root SYSTEM "MappingTable.dtd"><Root File-format="MDF" Menu-name="SDK DocInfo Extraction" Mac-creator="" Mac-type="TEXT" Win-suffix="DocInfo.txt" Encode-out="Utf-8-out">	<!--	ADOBE SYSTEMS INCORPORATED	Copyright 2003 Adobe Systems Incorporated	All Rights Reserved		NOTICE:  This Notice only applies to this file or any portion thereof.	Adobe permits you to use, modify, and distribute this file in accordance	with the terms and conditions of the Adobe license agreement accompanying	it ("Agreement").  Additionally, Adobe grants you a nonexclusive,	nontransferable, royalty-free license to use, modify and distribute	all or any portion of this file.  Where the terms of this Notice	and the terms of the Agreement differ, the terms of this Notice	shall control.  All other terms and conditions of the Agreement	remain unchanged and have full force and effect.  If you have received	this file from a source other than Adobe, then your use, modification,	or distribution of it requires the prior written permission of Adobe.-->	<!-- This sample extracts the meta-data from the document, saving it into a file called x.DocInfo.txt. -->	<!-- The event list deals with metadata items. 	 -->	<Define-proc-list Name="dump-metadata">		<Proc-var Pdf-var="Title" Owner="Metadata" Type="String" Inherit="Not-inherited" Condition="Has-value">			<Emit-string>Title=&quot;</Emit-string>			<Proc-string/>			<Emit-string NL-After="Yes">&quot;</Emit-string>		</Proc-var>		<Proc-var Pdf-var="Author" Owner="Metadata" Type="String" Inherit="Not-inherited" Condition="Has-value">			<Emit-string>Author=&quot;</Emit-string>			<Proc-string/>			<Emit-string NL-After="Yes">&quot;</Emit-string>		</Proc-var>		<Proc-var Pdf-var="Subject" Owner="Metadata" Type="String" Inherit="Not-inherited" Condition="Has-value">			<Emit-string>Subject=&quot;</Emit-string>			<Proc-string/>			<Emit-string NL-After="Yes">&quot;</Emit-string>		</Proc-var>		<Proc-var Pdf-var="Creator" Owner="Metadata" Type="String" Inherit="Not-inherited" Condition="Has-value">			<Emit-string>Creator=&quot;</Emit-string>			<Proc-string/>			<Emit-string NL-After="Yes">&quot;</Emit-string>		</Proc-var>		<Proc-var Pdf-var="CreationDate" Owner="Metadata" Type="String" Inherit="Not-inherited" Condition="Has-value">			<Emit-string>Date=&quot;</Emit-string>			<Proc-string/>			<Emit-string NL-After="Yes">&quot;</Emit-string>		</Proc-var>		<Proc-var Pdf-var="ModDate" Owner="Metadata" Type="String" Inherit="Not-inherited" Condition="Has-value">			<Emit-string>Date Modified=&quot;</Emit-string>			<Proc-string/>			<Emit-string NL-After="Yes">&quot;</Emit-string>		</Proc-var>	</Define-proc-list>	<!-- Walk the meta-data tree -->	<Walk-doc-metadata Use-proc-list="dump-metadata"/></Root>
